sudo: required
services:
  - docker


before_install:
  - docker build -t mityab/docker-react -f Dockerfile.dev .
  
script:
  - docker run mityab/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-816617190840"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key:
    secure: "$aws_secret_key"
